CalcPsychrometricsFromTWetBulb – MinimalDX
CalcPsychrometricsFromTWetBulb Subroutine
19 statements
Source File
public subroutine CalcPsychrometricsFromTWetBulb(TDryBulb, TWetBulb, Pressure, HumRatio, TDewPoint, RelHum, VapPres, MoistAirEnthalpy, MoistAirVolume, DegreeOfSaturation)
Utility function to calculate humidity ratio, dew-point temperature, relative humidity, vapour pressure, moist air enthalpy, moist air volume, and degree of saturation of air given dry-bulb temperature, wet-bulb temperature, and pressure.
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: TDryBulb
Dry-bulb temperature in °F [IP] or °C [SI]
real, intent(in) :: TWetBulb
Wet-bulb temperature in °F [IP] or °C [SI]
real, intent(in) :: Pressure
Atmospheric pressure in Psi [IP] or Pa [SI]
real, intent(out) :: HumRatio
Humidity ratio in lb_H₂O lb_Air⁻¹ [IP] or kg_H₂O kg_Air⁻¹ [SI]
real, intent(out) :: TDewPoint
Dew-point temperature in °F [IP] or °C [SI]
real, intent(out) :: RelHum
Relative humidity in range [0, 1]
real, intent(out) :: VapPres
Partial pressure of water vapor in moist air in Psi [IP] or Pa [SI]
real, intent(out) :: MoistAirEnthalpy
Moist air enthalpy in Btu lb⁻¹ [IP] or J kg⁻¹ [SI]
real, intent(out) :: MoistAirVolume
Specific volume of moist air in ft³ lb⁻¹ [IP] or in m³ kg⁻¹ [SI]
real, intent(out) :: DegreeOfSaturation
Degree of saturation [unitless]
Calls
Contents
Source Code
CalcPsychrometricsFromTWetBulb
Source Code
  subroutine CalcPsychrometricsFromTWetBulb(TDryBulb,           &
                                            TWetBulb,           &
                                            Pressure,           &
                                            HumRatio,           &
                                            TDewPoint,          &
                                            RelHum,             &
                                            VapPres,            &
                                            MoistAirEnthalpy,   &
                                            MoistAirVolume,     &
                                            DegreeOfSaturation)
    !+ Utility function to calculate humidity ratio, dew-point temperature, relative humidity,
    !+ vapour pressure, moist air enthalpy, moist air volume, and degree of saturation of air given
    !+ dry-bulb temperature, wet-bulb temperature, and pressure.
    real, intent(in)    ::  TDryBulb
      !+ Dry-bulb temperature in °F [IP] or °C [SI]
    real, intent(in)    ::  TWetBulb
      !+ Wet-bulb temperature in °F [IP] or °C [SI]
    real, intent(in)    ::  Pressure
      !+ Atmospheric pressure in Psi [IP] or Pa [SI]
    real, intent(out)   ::  HumRatio
      !+ Humidity ratio in lb_H₂O lb_Air⁻¹ [IP] or kg_H₂O kg_Air⁻¹ [SI]
    real, intent(out)   ::  TDewPoint
      !+ Dew-point temperature in °F [IP] or °C [SI]
    real, intent(out)   ::  RelHum
      !+ Relative humidity in range [0, 1]
    real, intent(out)   ::  VapPres
      !+ Partial pressure of water vapor in moist air in Psi [IP] or Pa [SI]
    real, intent(out)   ::  MoistAirEnthalpy
      !+ Moist air enthalpy in Btu lb⁻¹ [IP] or J kg⁻¹ [SI]
    real, intent(out)   ::  MoistAirVolume
      !+ Specific volume of moist air in ft³ lb⁻¹ [IP] or in m³ kg⁻¹ [SI]
    real, intent(out)   ::  DegreeOfSaturation
      !+ Degree of saturation [unitless]
    HumRatio            = GetHumRatioFromTWetBulb(TDryBulb, TWetBulb, Pressure)
    TDewPoint           = GetTDewPointFromHumRatio(TDryBulb, HumRatio, Pressure)
    RelHum              = GetRelHumFromHumRatio(TDryBulb, HumRatio, Pressure)
    VapPres             = GetVapPresFromHumRatio(HumRatio, Pressure)
    MoistAirEnthalpy    = GetMoistAirEnthalpy(TDryBulb, HumRatio)
    MoistAirVolume      = GetMoistAirVolume(TDryBulb, HumRatio, Pressure)
    DegreeOfSaturation  = GetDegreeOfSaturation(TDryBulb, HumRatio, Pressure)
  end subroutine CalcPsychrometricsFromTWetBulb
Call graph
calcpsychrometricsfromtwetbulb calls getvappresfromhumratio, getmoistairvolume, gethumratiofromtwetbulb, gettdewpointfromhumratio, getdegreeofsaturation, getmoistairenthalpy, getrelhumfromhumratio
getmoistairvolume calls isip, gettrankinefromtfahrenheit, gettkelvinfromtcelsius
gethumratiofromtwetbulb calls isip, getsathumratio
gettdewpointfromhumratio calls getvappresfromhumratio, gettdewpointfromvappres
getdegreeofsaturation calls getsathumratio
getmoistairenthalpy calls isip
getrelhumfromhumratio calls getvappresfromhumratio, getrelhumfromvappres
getsathumratio calls getsatvappres
getrelhumfromvappres calls getsatvappres
gettdewpointfromvappres calls isip, getsatvappres, dlnpws_
getsatvappres calls isip, gettrankinefromtfahrenheit, gettkelvinfromtcelsius
dlnpws_ calls isip, gettrankinefromtfahrenheit, gettkelvinfromtcelsius