CalcPsychrometricsFromTDewPoint – MinimalDX
CalcPsychrometricsFromTDewPoint Subroutine
19 statements
Source File
public subroutine CalcPsychrometricsFromTDewPoint(TDryBulb, TDewPoint, Pressure, HumRatio, TWetBulb, RelHum, VapPres, MoistAirEnthalpy, MoistAirVolume, DegreeOfSaturation)
Utility function to calculate humidity ratio, wet-bulb temperature, relative humidity, vapour pressure, moist air enthalpy, moist air volume, and degree of saturation of air given dry-bulb temperature, dew-point temperature, and pressure.
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: TDryBulb
Dry-bulb temperature in °F [IP] or °C [SI]
real, intent(in) :: TDewPoint
Dew-point temperature in °F [IP] or °C [SI]
real, intent(in) :: Pressure
Atmospheric pressure in Psi [IP] or Pa [SI]
real, intent(out) :: HumRatio
Humidity ratio in lb_H₂O lb_Air⁻¹ [IP] or kg_H₂O kg_Air⁻¹ [SI]
real, intent(out) :: TWetBulb
Wet-bulb temperature in °F [IP] or °C [SI]
real, intent(out) :: RelHum
Relative humidity in range [0, 1]
real, intent(out) :: VapPres
Partial pressure of water vapor in moist air in Psi [IP] or Pa [SI]
real, intent(out) :: MoistAirEnthalpy
Moist air enthalpy in Btu lb⁻¹ [IP] or J kg⁻¹ [SI]
real, intent(out) :: MoistAirVolume
Specific volume of moist air in ft³ lb⁻¹ [IP] or in m³ kg⁻¹ [SI]
real, intent(out) :: DegreeOfSaturation
Degree of saturation [unitless]
Calls
Contents
Source Code
CalcPsychrometricsFromTDewPoint
Source Code
  subroutine CalcPsychrometricsFromTDewPoint(TDryBulb,           &
                                             TDewPoint,          &
                                             Pressure,           &
                                             HumRatio,           &
                                             TWetBulb,           &
                                             RelHum,             &
                                             VapPres,            &
                                             MoistAirEnthalpy,   &
                                             MoistAirVolume,     &
                                             DegreeOfSaturation)
    !+ Utility function to calculate humidity ratio, wet-bulb temperature, relative humidity,
    !+ vapour pressure, moist air enthalpy, moist air volume, and degree of saturation of air given
    !+ dry-bulb temperature, dew-point temperature, and pressure.
    real, intent(in)    ::  TDryBulb
      !+ Dry-bulb temperature in °F [IP] or °C [SI]
    real, intent(in)    ::  TDewPoint
      !+ Dew-point temperature in °F [IP] or °C [SI]
    real, intent(in)    ::  Pressure
      !+ Atmospheric pressure in Psi [IP] or Pa [SI]
    real, intent(out)   ::  HumRatio
      !+ Humidity ratio in lb_H₂O lb_Air⁻¹ [IP] or kg_H₂O kg_Air⁻¹ [SI]
    real, intent(out)   ::  TWetBulb
      !+ Wet-bulb temperature in °F [IP] or °C [SI]
    real, intent(out)   ::  RelHum
      !+ Relative humidity in range [0, 1]
    real, intent(out)   ::  VapPres
      !+ Partial pressure of water vapor in moist air in Psi [IP] or Pa [SI]
    real, intent(out)   ::  MoistAirEnthalpy
      !+ Moist air enthalpy in Btu lb⁻¹ [IP] or J kg⁻¹ [SI]
    real, intent(out)   ::  MoistAirVolume
      !+ Specific volume of moist air in ft³ lb⁻¹ [IP] or in m³ kg⁻¹ [SI]
    real, intent(out)   ::  DegreeOfSaturation
      !+ Degree of saturation [unitless]
    HumRatio            = GetHumRatioFromTDewPoint(TDewPoint, Pressure)
    TWetBulb            = GetTWetBulbFromHumRatio(TDryBulb, HumRatio, Pressure)
    RelHum              = GetRelHumFromHumRatio(TDryBulb, HumRatio, Pressure)
    VapPres             = GetVapPresFromHumRatio(HumRatio, Pressure)
    MoistAirEnthalpy    = GetMoistAirEnthalpy(TDryBulb, HumRatio)
    MoistAirVolume      = GetMoistAirVolume(TDryBulb, HumRatio, Pressure)
    DegreeOfSaturation  = GetDegreeOfSaturation(TDryBulb, HumRatio, Pressure)
  end subroutine CalcPsychrometricsFromTDewPoint
Call graph
calcpsychrometricsfromtdewpoint calls getvappresfromhumratio, getmoistairvolume, gethumratiofromtdewpoint, gettwetbulbfromhumratio, getdegreeofsaturation, getmoistairenthalpy, getrelhumfromhumratio
getmoistairvolume calls isip, gettrankinefromtfahrenheit, gettkelvinfromtcelsius
gethumratiofromtdewpoint calls gethumratiofromvappres, getsatvappres
gettwetbulbfromhumratio calls gethumratiofromtwetbulb, gettdewpointfromhumratio
getdegreeofsaturation calls getsathumratio
getmoistairenthalpy calls isip
getrelhumfromhumratio calls getvappresfromhumratio, getrelhumfromvappres
getsathumratio calls getsatvappres
gethumratiofromtwetbulb calls isip, getsathumratio
getrelhumfromvappres calls getsatvappres
gettdewpointfromhumratio calls getvappresfromhumratio, gettdewpointfromvappres
getsatvappres calls isip, gettrankinefromtfahrenheit, gettkelvinfromtcelsius
gettdewpointfromvappres calls isip, getsatvappres, dlnpws_
dlnpws_ calls isip, gettrankinefromtfahrenheit, gettkelvinfromtcelsius