GetHumRatioFromTDewPoint – MinimalDX
GetHumRatioFromTDewPoint Function
8 statements
Source File
public function GetHumRatioFromTDewPoint(TDewPoint, Pressure) result(HumRatio)
Return humidity ratio given dew-point temperature and pressure. Reference: ASHRAE Handbook - Fundamentals (2017) ch. 1
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: TDewPoint
Dew-point temperature in °F [IP] or °C [SI]
real, intent(in) :: Pressure
Atmospheric pressure in Psi [IP] or Pa [SI]
Return Value real
Humidity ratio in lb_H₂O lb_Air⁻¹ [IP] or kg_H₂O kg_Air⁻¹ [SI]
Calls
Called by
Contents
Source Code
GetHumRatioFromTDewPoint
Source Code
  function GetHumRatioFromTDewPoint(TDewPoint, Pressure) result(HumRatio)
    !+ Return humidity ratio given dew-point temperature and pressure.
    !+ Reference:
    !+ ASHRAE Handbook - Fundamentals (2017) ch. 1
    real, intent(in)  ::  TDewPoint
      !+ Dew-point temperature in °F [IP] or °C [SI]
    real, intent(in)  ::  Pressure
      !+ Atmospheric pressure in Psi [IP] or Pa [SI]
    real              ::  HumRatio
      !+ Humidity ratio in lb_H₂O lb_Air⁻¹ [IP] or kg_H₂O kg_Air⁻¹ [SI]
    real              ::  VapPres
      !+ Partial pressure of water vapor in moist air in Psi [IP] or Pa [SI]
    VapPres   = GetSatVapPres(TDewPoint)
    HumRatio  = GetHumRatioFromVapPres(VapPres, Pressure)
  end function GetHumRatioFromTDewPoint
Call graph
gethumratiofromtdewpoint calls getsatvappres, gethumratiofromvappres
getsatvappres calls isip, gettrankinefromtfahrenheit, gettkelvinfromtcelsius
gettwetbulbfromtdewpoint calls gethumratiofromtdewpoint
calcpsychrometricsfromtdewpoint calls gethumratiofromtdewpoint