GetHumRatioFromRelHum – MinimalDX
GetHumRatioFromRelHum Function
12 statements
Source File
public function GetHumRatioFromRelHum(TDryBulb, RelHum, Pressure) result(HumRatio)
Return humidity ratio given dry-bulb temperature, relative humidity, and pressure. Reference: ASHRAE Handbook - Fundamentals (2017) ch. 1
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: TDryBulb
Dry-bulb temperature in °F [IP] or °C [SI]
real, intent(in) :: RelHum
Relative humidity in range [0, 1]
real, intent(in) :: Pressure
Atmospheric pressure in Psi [IP] or Pa [SI]
Return Value real
Humidity ratio in lb_H₂O lb_Air⁻¹ [IP] or kg_H₂O kg_Air⁻¹ [SI]
Calls
Called by
Contents
Source Code
GetHumRatioFromRelHum
Source Code
  function GetHumRatioFromRelHum(TDryBulb, RelHum, Pressure) result(HumRatio)
    !+ Return humidity ratio given dry-bulb temperature, relative humidity, and pressure.
    !+ Reference:
    !+ ASHRAE Handbook - Fundamentals (2017) ch. 1
    real, intent(in)  ::  TDryBulb
      !+ Dry-bulb temperature in °F [IP] or °C [SI]
    real, intent(in)  ::  RelHum
      !+ Relative humidity in range [0, 1]
    real, intent(in)  ::  Pressure
      !+ Atmospheric pressure in Psi [IP] or Pa [SI]
    real              ::  HumRatio
      !+ Humidity ratio in lb_H₂O lb_Air⁻¹ [IP] or kg_H₂O kg_Air⁻¹ [SI]
    real              ::  VapPres
      !+ Partial pressure of water vapor in moist air in Psi [IP] or Pa [SI]
    if (RelHum < 0.0 .or. RelHum > 1.0) then
      error stop "Error: relative humidity is outside range [0,1]"
    end if
    VapPres   = GetVapPresFromRelHum(TDryBulb, RelHum)
    HumRatio  = GetHumRatioFromVapPres(VapPres, Pressure)
  end function GetHumRatioFromRelHum
Call graph
gethumratiofromrelhum calls getvappresfromrelhum, gethumratiofromvappres
getvappresfromrelhum calls getsatvappres
getsatvappres calls isip, gettrankinefromtfahrenheit, gettkelvinfromtcelsius
gettwetbulbfromrelhum calls gethumratiofromrelhum
calcpsychrometricsfromrelhum calls gethumratiofromrelhum