GetRelHumFromVapPres – MinimalDX
GetRelHumFromVapPres Function
9 statements
Source File
public function GetRelHumFromVapPres(TDryBulb, VapPres) result(RelHum)
Return relative humidity given dry-bulb temperature and vapor pressure. References: ASHRAE Handbook - Fundamentals (2017) ch. 1 eqn 12, 22
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: TDryBulb
Dry-bulb temperature in 째F [IP] or 째C [SI]
real, intent(in) :: VapPres
Partial pressure of water vapor in moist air in Psi [IP] or Pa [SI]
Return Value real
Relative humidity in range [0, 1]
Calls
Called by
Contents
Source Code
GetRelHumFromVapPres
Source Code
  function GetRelHumFromVapPres(TDryBulb, VapPres) result(RelHum)
    !+ Return relative humidity given dry-bulb temperature and vapor pressure.
    !+ References:
    !+ ASHRAE Handbook - Fundamentals (2017) ch. 1 eqn 12, 22
    real, intent(in)  ::  TDryBulb
      !+ Dry-bulb temperature in 째F [IP] or 째C [SI]
    real, intent(in)  ::  VapPres
      !+ Partial pressure of water vapor in moist air in Psi [IP] or Pa [SI]
    real              ::  RelHum
      !+ Relative humidity in range [0, 1]
    if (VapPres < 0.0) then
      error stop "Error: partial pressure of water vapor in moist air cannot be negative"
    end if
    RelHum = VapPres / GetSatVapPres(TDryBulb)
  end function GetRelHumFromVapPres
Call graph
getrelhumfromvappres calls getsatvappres
getsatvappres calls isip, gettrankinefromtfahrenheit, gettkelvinfromtcelsius
getrelhumfromhumratio calls getrelhumfromvappres
calcpsychrometricsfromtwetbulb calls getrelhumfromhumratio
getrelhumfromtwetbulb calls getrelhumfromhumratio
calcpsychrometricsfromtdewpoint calls getrelhumfromhumratio
getvaporpressuredeficit calls getrelhumfromhumratio