GetSatHumRatio – MinimalDX
GetSatHumRatio Function
9 statements
Source File
public function GetSatHumRatio(TDryBulb, Pressure) result(SatHumRatio)
Return humidity ratio of saturated air given dry-bulb temperature and pressure. Reference: ASHRAE Handbook - Fundamentals (2017) ch. 1 eqn 36, solved for W
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: TDryBulb
Dry-bulb temperature in °F [IP] or °C [SI]
real, intent(in) :: Pressure
Atmospheric pressure in Psi [IP] or Pa [SI]
Return Value real
Humidity ratio of saturated air in lb_H₂O lb_Air⁻¹ [IP] or kg_H₂O kg_Air⁻¹ [SI]
Calls
Called by
Contents
Source Code
GetSatHumRatio
Source Code
  function GetSatHumRatio(TDryBulb, Pressure) result(SatHumRatio)
    !+ Return humidity ratio of saturated air given dry-bulb temperature and pressure.
    !+ Reference:
    !+ ASHRAE Handbook - Fundamentals (2017) ch. 1 eqn 36, solved for W
    real, intent(in)  ::  TDryBulb
      !+ Dry-bulb temperature in °F [IP] or °C [SI]
    real, intent(in)  ::  Pressure
      !+ Atmospheric pressure in Psi [IP] or Pa [SI]
    real              ::  SatHumRatio
      !+ Humidity ratio of saturated air in lb_H₂O lb_Air⁻¹ [IP] or kg_H₂O kg_Air⁻¹ [SI]
    real              ::  SatVaporPres
      !+ Vapor pressure of saturated air in in lb_H₂O lb_Air⁻¹ [IP] or kg_H₂O kg_Air⁻¹ [SI]
    SatVaporPres  = GetSatVapPres(TDryBulb)
    SatHumRatio   = 0.621945 * SatVaporPres / (Pressure-SatVaporPres)
    ! Validity check.
    SatHumRatio = max(SatHumRatio, MIN_HUM_RATIO)
  end function GetSatHumRatio
Call graph
getsathumratio calls getsatvappres
getsatvappres calls isip, gettrankinefromtfahrenheit, gettkelvinfromtcelsius
getsatairenthalpy calls getsathumratio
getdegreeofsaturation calls getsathumratio
gethumratiofromtwetbulb calls getsathumratio
gettdewpointfromtwetbulb calls gethumratiofromtwetbulb
gettwetbulbfromhumratio calls gethumratiofromtwetbulb
psytsatfnhpb calls getsatairenthalpy
calcpsychrometricsfromtdewpoint calls getdegreeofsaturation, gettwetbulbfromhumratio
calcpsychrometricsfromtwetbulb calls getdegreeofsaturation, gethumratiofromtwetbulb
calcpsychrometricsfromrelhum calls getdegreeofsaturation, gettwetbulbfromhumratio
getrelhumfromtwetbulb calls gethumratiofromtwetbulb
calcminimaldxcooling calls gettwetbulbfromhumratio, psytsatfnhpb
gettwetbulbfromrelhum calls gettwetbulbfromhumratio
gettwetbulbfromtdewpoint calls gettwetbulbfromhumratio
simminimaldxcooling calls calcminimaldxcooling