GetStationPressure – MinimalDX
GetStationPressure Function
7 statements
Source File
public function GetStationPressure(SeaLevelPressure, Altitude, TDryBulb) result(StationPressure)
Return station pressure from sea level pressure. Reference: See 'GetSeaLevelPressure' Notes: This function is just the inverse of 'GetSeaLevelPressure'.
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: SeaLevelPressure
Sea level barometric pressure in Psi [IP] or Pa [SI]
real, intent(in) :: Altitude
Altitude in ft [IP] or m [SI]
real, intent(in) :: TDryBulb
Dry-bulb temperature in 째F [IP] or 째C [SI]
Return Value real
Station pressure in Psi [IP] or Pa [SI]
Calls
Contents
Source Code
GetStationPressure
Source Code
  function GetStationPressure(SeaLevelPressure, Altitude, TDryBulb) result(StationPressure)
    !+ Return station pressure from sea level pressure.
    !+ Reference:
    !+ See 'GetSeaLevelPressure'
    !+ Notes:
    !+ This function is just the inverse of 'GetSeaLevelPressure'.
    real, intent(in)  ::  SeaLevelPressure
      !+ Sea level barometric pressure in Psi [IP] or Pa [SI]
    real, intent(in)  ::  Altitude
      !+ Altitude in ft [IP] or m [SI]
    real, intent(in)  ::  TDryBulb
      !+ Dry-bulb temperature in 째F [IP] or 째C [SI]
    real              ::  StationPressure
      !+ Station pressure in Psi [IP] or Pa [SI]
    StationPressure = SeaLevelPressure / GetSeaLevelPressure(1.0, Altitude, TDryBulb)
  end function GetStationPressure
Call graph
getstationpressure calls getsealevelpressure
getsealevelpressure calls isip, gettrankinefromtfahrenheit, gettkelvinfromtcelsius