GetSatAirEnthalpy – MinimalDX
GetSatAirEnthalpy Function
6 statements
Source File
public function GetSatAirEnthalpy(TDryBulb, Pressure) result(SatAirEnthalpy)
Return saturated air enthalpy given dry-bulb temperature and pressure. Reference: ASHRAE Handbook - Fundamentals (2017) ch. 1
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: TDryBulb
Dry-bulb temperature in °F [IP] or °C [SI]
real, intent(in) :: Pressure
Atmospheric pressure in Psi [IP] or Pa [SI]
Return Value real
Saturated air enthalpy in Btu lb⁻¹ [IP] or J kg⁻¹ [SI]
Calls
Called by
Contents
Source Code
GetSatAirEnthalpy
Source Code
  function GetSatAirEnthalpy(TDryBulb, Pressure) result(SatAirEnthalpy)
    !+ Return saturated air enthalpy given dry-bulb temperature and pressure.
    !+ Reference:
    !+ ASHRAE Handbook - Fundamentals (2017) ch. 1
    real, intent(in)  ::  TDryBulb
      !+ Dry-bulb temperature in °F [IP] or °C [SI]
    real, intent(in)  ::  Pressure
      !+ Atmospheric pressure in Psi [IP] or Pa [SI]
    real              ::  SatAirEnthalpy
      !+ Saturated air enthalpy in Btu lb⁻¹ [IP] or J kg⁻¹ [SI]
    SatAirEnthalpy = GetMoistAirEnthalpy(TDryBulb, GetSatHumRatio(TDryBulb, Pressure))
  end function GetSatAirEnthalpy
Call graph
getsatairenthalpy calls getsathumratio, getmoistairenthalpy
getsathumratio calls getsatvappres
getmoistairenthalpy calls isip
getsatvappres calls isip, gettrankinefromtfahrenheit, gettkelvinfromtcelsius
psytsatfnhpb calls getsatairenthalpy
calcminimaldxcooling calls psytsatfnhpb
simminimaldxcooling calls calcminimaldxcooling