GetTWetBulbFromTDewPoint – MinimalDX
GetTWetBulbFromTDewPoint Function
12 statements
Source File
public function GetTWetBulbFromTDewPoint(TDryBulb, TDewPoint, Pressure) result(TWetBulb)
Return wet-bulb temperature given dry-bulb temperature, dew-point temperature, and pressure. References: ASHRAE Handbook - Fundamentals (2017) ch. 1
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: TDryBulb
Dry-bulb temperature in °F [IP] or °C [SI]
real, intent(in) :: TDewPoint
Dew-point temperature in °F [IP] or °C [SI]
real, intent(in) :: Pressure
Atmospheric pressure in Psi [IP] or Pa [SI]
Return Value real
Wet-bulb temperature in °F [IP] or °C [SI]
Calls
Contents
Source Code
GetTWetBulbFromTDewPoint
Source Code
  function GetTWetBulbFromTDewPoint(TDryBulb, TDewPoint, Pressure) result(TWetBulb)
    !+ Return wet-bulb temperature given dry-bulb temperature, dew-point temperature, and pressure.
    !+ References:
    !+ ASHRAE Handbook - Fundamentals (2017) ch. 1
    real, intent(in)  :: TDryBulb
      !+ Dry-bulb temperature in °F [IP] or °C [SI]
    real, intent(in)  :: TDewPoint
      !+ Dew-point temperature in °F [IP] or °C [SI]
    real, intent(in)  :: Pressure
      !+ Atmospheric pressure in Psi [IP] or Pa [SI]
    real              :: TWetBulb
      !+ Wet-bulb temperature in °F [IP] or °C [SI]
    real              :: HumRatio
      !+ Humidity ratio in lb_H₂O lb_Air⁻¹ [IP] or kg_H₂O kg_Air⁻¹ [SI]
    if (TDewPoint > TDryBulb) then
      error stop "Error: dew point temperature is above dry bulb temperature"
    end if
    HumRatio = GetHumRatioFromTDewPoint(TDewPoint, Pressure)
    TWetBulb = GetTWetBulbFromHumRatio(TDryBulb, HumRatio, Pressure)
  end function GetTWetBulbFromTDewPoint
Call graph
gettwetbulbfromtdewpoint calls gethumratiofromtdewpoint, gettwetbulbfromhumratio
gethumratiofromtdewpoint calls getsatvappres, gethumratiofromvappres
gettwetbulbfromhumratio calls gettdewpointfromhumratio, gethumratiofromtwetbulb
gettdewpointfromhumratio calls getvappresfromhumratio, gettdewpointfromvappres
getsatvappres calls isip, gettrankinefromtfahrenheit, gettkelvinfromtcelsius
gethumratiofromtwetbulb calls isip, getsathumratio
getsathumratio calls getsatvappres
gettdewpointfromvappres calls getsatvappres, isip, dlnpws_
dlnpws_ calls isip, gettrankinefromtfahrenheit, gettkelvinfromtcelsius