GetTKelvinFromTCelsius – MinimalDX
GetTKelvinFromTCelsius Function
5 statements
Source File
public function GetTKelvinFromTCelsius(TCelsius) result(TKelvin)
Utility function to convert temperature to Kelvin (K) given temperature in degree Celsius (°C). Reference: ASHRAE Handbook - Fundamentals (2017) ch. 1 section 3
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: TCelsius
Temperature in degree Celsius
Return Value real
Tempearatyre in Kelvin
Called by
Contents
Source Code
GetTKelvinFromTCelsius
Source Code
  function GetTKelvinFromTCelsius(TCelsius) result(TKelvin)
    !+ Utility function to convert temperature to Kelvin (K)
    !+ given temperature in degree Celsius (°C).
    !+ Reference: ASHRAE Handbook - Fundamentals (2017) ch. 1 section 3
    real, intent(in)  :: TCelsius
      !+ Temperature in degree Celsius
    real              :: TKelvin
      !+ Tempearatyre in Kelvin
    TKelvin = TCelsius + ZERO_CELSIUS_AS_KELVIN
  end function GetTKelvinFromTCelsius
Call graph
getdryairdensity calls gettkelvinfromtcelsius
getdryairvolume calls gettkelvinfromtcelsius
getmoistairvolume calls gettkelvinfromtcelsius
dlnpws_ calls gettkelvinfromtcelsius
getsealevelpressure calls gettkelvinfromtcelsius
getsatvappres calls gettkelvinfromtcelsius
getsathumratio calls getsatvappres
getrelhumfromtdewpoint calls getsatvappres
getmoistairdensity calls getmoistairvolume
gethumratiofromtdewpoint calls getsatvappres
getrelhumfromvappres calls getsatvappres
getvappresfromtdewpoint calls getsatvappres
getstationpressure calls getsealevelpressure
calcpsychrometricsfromtdewpoint calls getmoistairvolume, gethumratiofromtdewpoint, getdegreeofsaturation, getrelhumfromhumratio, gettwetbulbfromhumratio
calcpsychrometricsfromtwetbulb calls getmoistairvolume, gethumratiofromtwetbulb, getdegreeofsaturation, gettdewpointfromhumratio, getrelhumfromhumratio
getvappresfromrelhum calls getsatvappres
calcpsychrometricsfromrelhum calls getmoistairvolume, gethumratiofromrelhum, getdegreeofsaturation, gettdewpointfromhumratio, gettwetbulbfromhumratio
getvaporpressuredeficit calls getsatvappres, getrelhumfromhumratio
gettdewpointfromvappres calls dlnpws_, getsatvappres
calcminimaldxcooling calls getmoistairdensity, gettwetbulbfromhumratio, psytsatfnhpb
getsatairenthalpy calls getsathumratio
gettdewpointfromrelhum calls getvappresfromrelhum, gettdewpointfromvappres
gethumratiofromrelhum calls getvappresfromrelhum
gethumratiofromtwetbulb calls getsathumratio
gettwetbulbfromtdewpoint calls gethumratiofromtdewpoint, gettwetbulbfromhumratio
getdegreeofsaturation calls getsathumratio
gettdewpointfromhumratio calls gettdewpointfromvappres
getrelhumfromhumratio calls getrelhumfromvappres
gettdewpointfromtwetbulb calls gethumratiofromtwetbulb, gettdewpointfromhumratio
gettwetbulbfromhumratio calls gethumratiofromtwetbulb, gettdewpointfromhumratio
psytsatfnhpb calls getsatairenthalpy
gettwetbulbfromrelhum calls gethumratiofromrelhum, gettwetbulbfromhumratio
simminimaldxcooling calls calcminimaldxcooling
getrelhumfromtwetbulb calls gethumratiofromtwetbulb, getrelhumfromhumratio