GetVapPresFromRelHum – MinimalDX
GetVapPresFromRelHum Function
9 statements
Source File
public function GetVapPresFromRelHum(TDryBulb, RelHum) result(VapPres)
Return partial pressure of water vapor as a function of relative humidity and temperature. References: ASHRAE Handbook - Fundamentals (2017) ch. 1 eqn 12, 22
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: TDryBulb
Dry-bulb temperature in 째F [IP] or 째C [SI]
real, intent(in) :: RelHum
Relative humidity in range [0, 1]
Return Value real
Partial pressure of water vapor in moist air in Psi [IP] or Pa [SI]
Calls
Called by
Contents
Source Code
GetVapPresFromRelHum
Source Code
  function GetVapPresFromRelHum(TDryBulb, RelHum) result(VapPres)
    !+ Return partial pressure of water vapor as a function of relative humidity and temperature.
    !+ References:
    !+ ASHRAE Handbook - Fundamentals (2017) ch. 1 eqn 12, 22
    real, intent(in)  ::  TDryBulb
      !+ Dry-bulb temperature in 째F [IP] or 째C [SI]
    real, intent(in)  ::  RelHum
      !+ Relative humidity in range [0, 1]
    real              ::  VapPres
      !+ Partial pressure of water vapor in moist air in Psi [IP] or Pa [SI]
    if (RelHum < 0.0 .or. RelHum > 1.0) then
      error stop "Error: relative humidity is outside range [0,1]"
    end if
    VapPres = RelHum * GetSatVapPres(TDryBulb)
  end function GetVapPresFromRelHum
Call graph
getvappresfromrelhum calls getsatvappres
getsatvappres calls isip, gettrankinefromtfahrenheit, gettkelvinfromtcelsius
gettdewpointfromrelhum calls getvappresfromrelhum
gethumratiofromrelhum calls getvappresfromrelhum
gettwetbulbfromrelhum calls gethumratiofromrelhum
calcpsychrometricsfromrelhum calls gethumratiofromrelhum