isIP – MinimalDX
isIP Function
10 statements
Source File
public function isIP()
Check whether the system in use is IP or SI
Arguments
None
Return Value logical
Called by
Contents
Source Code
isIP
Source Code
  function isIP()
    !+ Check whether the system in use is IP or SI
    logical :: isIP
    if (PSYCHROLIB_UNITS == IP) then
      isIP = .true.
    else if (PSYCHROLIB_UNITS == SI) then
      isIP = .false.
    else
      error stop "The system of units has not been defined."
    end if
  end function isIP
Call graph
getdryairenthalpy calls isip
getdryairdensity calls isip
getdryairvolume calls isip
getmoistairvolume calls isip
getstandardatmtemperature calls isip
gethumratiofromtwetbulb calls isip, getsathumratio
dlnpws_ calls isip
gettdrybulbfromenthalpyandhumratio calls isip
gethumratiofromenthalpyandtdrybulb calls isip
getsealevelpressure calls isip
getmoistairenthalpy calls isip
getstandardatmpressure calls isip
getsatvappres calls isip
gettdrybulbfrommoistairvolumeandhumratio calls isip
gettdewpointfromvappres calls isip, dlnpws_, getsatvappres
gettdewpointfromrelhum calls gettdewpointfromvappres, getvappresfromrelhum
getrelhumfromvappres calls getsatvappres
calcpsychrometricsfromtdewpoint calls getmoistairvolume, getmoistairenthalpy, gettwetbulbfromhumratio, gethumratiofromtdewpoint, getdegreeofsaturation, getrelhumfromhumratio
getvappresfromrelhum calls getsatvappres
getrelhumfromtdewpoint calls getsatvappres
getrelhumfromtwetbulb calls gethumratiofromtwetbulb, getrelhumfromhumratio
getvaporpressuredeficit calls getsatvappres, getrelhumfromhumratio
getsatairenthalpy calls getmoistairenthalpy, getsathumratio
getsathumratio calls getsatvappres
gettdewpointfromtwetbulb calls gethumratiofromtwetbulb, gettdewpointfromhumratio
getmoistairdensity calls getmoistairvolume
gettwetbulbfromhumratio calls gethumratiofromtwetbulb, gettdewpointfromhumratio
getstationpressure calls getsealevelpressure
gettdewpointfromhumratio calls gettdewpointfromvappres
calcminimaldxcooling calls gettdrybulbfromenthalpyandhumratio, gethumratiofromenthalpyandtdrybulb, getmoistairenthalpy, getmoistairdensity, gettwetbulbfromhumratio, psytsatfnhpb
getvappresfromtdewpoint calls getsatvappres
calcpsychrometricsfromtwetbulb calls getmoistairvolume, gethumratiofromtwetbulb, getmoistairenthalpy, gettdewpointfromhumratio, getdegreeofsaturation, getrelhumfromhumratio
gethumratiofromtdewpoint calls getsatvappres
calcpsychrometricsfromrelhum calls getmoistairvolume, getmoistairenthalpy, gettwetbulbfromhumratio, gettdewpointfromhumratio, gethumratiofromrelhum, getdegreeofsaturation
gethumratiofromrelhum calls getvappresfromrelhum
psytsatfnhpb calls getsatairenthalpy
getdegreeofsaturation calls getsathumratio
gettwetbulbfromrelhum calls gettwetbulbfromhumratio, gethumratiofromrelhum
gettwetbulbfromtdewpoint calls gettwetbulbfromhumratio, gethumratiofromtdewpoint
simminimaldxcooling calls calcminimaldxcooling
getrelhumfromhumratio calls getrelhumfromvappres