PsyTsatFnHPb – MinimalDX
PsyTsatFnHPb Function
108 statements
Source File
public function PsyTsatFnHPb(H, PB, calledfrom) result(T)
Uses
psychrolib
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: H
real, intent(in) :: PB
character(len=*), intent(in), optional :: calledfrom
Return Value real
Calls
Called by
Contents
Source Code
PsyTsatFnHPb
Source Code
  FUNCTION PsyTsatFnHPb(H,PB,calledfrom) RESULT(T)
            ! FUNCTION INFORMATION:
            !       AUTHOR         George Shih
            !       DATE WRITTEN   May 1976
            !       MODIFIED       July 2003; LKL -- peg min/max values (outside range of functions)
            !       RE-ENGINEERED  na
            ! PURPOSE OF THIS FUNCTION:
            ! This function provides the saturation temperature from the enthalpy
            ! and barometric pressure.
            ! METHODOLOGY EMPLOYED:
            ! na
            ! REFERENCES:
            ! ASHRAE HANDBOOK OF FUNDAMENTALS, 1972, P99, EQN 22
            ! USE STATEMENTS:
            USE psychrolib, ONLY: GetSatAirEnthalpy
    IMPLICIT NONE    ! Enforce explicit typing of all variables in this routine
            ! FUNCTION ARGUMENT DEFINITIONS:
        REAL, intent(in) :: H      ! enthalpy {J/kg}
        REAL, intent(in) :: PB     ! barometric pressure {Pascals}
        character(len=*), intent(in), optional :: calledfrom  ! routine this function was called from (error messages)
        REAL        :: T      ! result=> saturation temperature {C}
            ! FUNCTION PARAMETER DEFINITIONS:
            ! na
            ! INTERFACE BLOCK SPECIFICATIONS
            ! na
            ! DERIVED TYPE DEFINITIONS
            ! na
            ! FUNCTION LOCAL VARIABLE DECLARATIONS:
        REAL T1  ! APPROXIMATE SATURATION TEMPERATURE (C)
        REAL T2  ! APPROXIMATE SATURATION TEMPERATURE (C)
        REAL TN  ! NEW ASSUMED SATURATION TEMPERATURE (C)
        REAL H1  ! APPROXIMATE ENTHALPY (J/KG)
        REAL H2  ! APPROXIMATE ENTHALPY (J/KG)
        REAL Y1  ! ERROR IN ENTHALPY
        REAL Y2  ! ERROR IN ENTHALPY
        INTEGER  IterCount
        REAL HH  ! temporary enthalpy (calculation) value
        LOGICAL FlagError  ! Set when errors should be flagged
        REAL      :: Hloc ! local value of H
  !                                      CHECK H IN RANGE.
        HH = H + 1.78637e4
        IF (H >= 0.) THEN
          Hloc = MAX(0.00001,H)
        ELSE IF (H < 0.) THEN
          Hloc = MIN(-.00001,H)
        END IF
        FlagError=.false.
  !
        IF (HH > 7.5222e4) GO TO 20
        IF (HH > 2.7297e4) GO TO 60
        IF (HH > -6.7012e2) GO TO 50
        IF (HH > -2.2138e4) GO TO 40
        IF (HH < -4.24e4) HH=-4.24e4   ! Peg to minimum
        GO TO 30
    20 CONTINUE
        IF (HH < 1.8379e5) GO TO 70
        IF (HH < 4.7577e5) GO TO 80
        IF (HH < 1.5445e6) GO TO 90
        IF (HH < 3.8353e6) GO TO 100
        IF (HH > 4.5866e7) HH=4.5866e7   ! Peg to maximum
        GO TO 110
  !
  !                                      TEMP. IS FROM -60 C  TO  -40 C
    30 CONTINUE
        T=F6(HH,-19.44e0,8.53675e-4,-5.12637e-9,-9.85546e-14,-1.00102e-18,-4.2705e-24)
        GO TO 120
  !                                      TEMP. IS FROM -40 C  TO  -20 C
    40 CONTINUE
        T=F6(HH,-1.94224e1,8.5892e-4,-4.50709e-9,-6.19492e-14,8.71734e-20,8.73051e-24)
        GO TO 120
  !                                      TEMP. IS FROM -20 C  TO    0 C
    50 CONTINUE
        T=F6(HH,-1.94224e1,8.59061e-4,-4.4875e-9,-5.76696e-14,7.72217e-19,3.97894e-24)
        GO TO 120
  !                                      TEMP. IS FROM   0 C  TO   20 C
    60 CONTINUE
        T=F6(HH,-2.01147e1,9.04936e-4,-6.83305e-9,2.3261e-14,7.27237e-20,-6.31939e-25)
        GO TO 120
  !                                      TEMP. IS FROM  20 C  TO   40 C
    70 CONTINUE
        T=F6(HH,-1.82124e1,8.31683e-4,-6.16461e-9,3.06411e-14,-8.60964e-20,1.03003e-25)
        GO TO 120
  !                                      TEMP. IS FROM  40 C  TO   60 C
    80 CONTINUE
        T=F6(HH,-1.29419e0,3.88538e-4,-1.30237e-9,2.78254e-15,-3.27225e-21,1.60969e-27)
        GO TO 120
  !                                      TEMP. IS FROM   60 C TO   80 C
    90 CONTINUE
        T=F6(HH,2.39214e1,1.27519e-4,-1.52089e-10,1.1043e-16,-4.33919e-23,7.05296e-30)
        GO TO 120
  !                                      TEMP. IS FROM   80 C TO   90 C
    100 CONTINUE
        T=F6(HH,4.88446e1,3.85534e-5,-1.78805e-11,4.87224e-18,-7.15283e-25,4.36246e-32)
        GO TO 120
  !                                      TEMP. IS FROM   90 C TO  100C
    110 CONTINUE
        T=F7(HH,7.60565e11,5.80534e4,-7.36433e-3,5.11531e-10,-1.93619e-17,3.70511e-25, -2.77313e-33)
  !                                      IF THE BAROMETRIC PRESSURE IS
  !                                      EQUAL TO 1.0133E5 , SATURATION
  !                                      TEMP. IS CALCULATED BY ABOVE EQUA
  !                                      OTHERWISE TEMP. IS COMPUTED BY
  !                                      FOLLOWING ITERATION METHOD
    120 CONTINUE
        IF (ABS(PB-1.0133e5)/1.0133e5 <= 0.01) GO TO 170
        IterCount=0
        T1=T
        H1=GetSatAirEnthalpy(T1,PB)
        Y1=H1-Hloc
        IF (ABS(Y1/Hloc) <= 0.1e-4) GO TO 140
        T2=T1*0.9
    130 IterCount=IterCount+1
        H2=GetSatAirEnthalpy(T2,PB)
        Y2=H2-Hloc
        IF (ABS(Y2/Hloc) <= 0.1e-4) GO TO 150
        IF (Y2 == Y1) GO TO 150
        TN=T2-Y2/(Y2-Y1)*(T2-T1)
        IF (IterCount > 30) GO TO 160
        T1=T2
        T2=TN
        Y1=Y2
        GO TO 130
    140 CONTINUE
        T=T1
        GO TO 170
    150 CONTINUE
        T=T2
        GO TO 170
    160 CONTINUE
    170 CONTINUE
  !   result is T
    RETURN
    CONTAINS
        REAL FUNCTION F6(X,A0,A1,A2,A3,A4,A5)
        IMPLICIT NONE
        REAL X
        REAL A0,A1,A2,A3,A4,A5
        F6=A0+X*(A1+X*(A2+X*(A3+X*(A4+X*A5))))
        RETURN
        END FUNCTION F6
        REAL FUNCTION F7(X,A0,A1,A2,A3,A4,A5,A6)
        IMPLICIT NONE
        REAL X,A6
        REAL A0,A1,A2,A3,A4,A5
        F7=(A0+X*(A1+X*(A2+X*(A3+X*(A4+X*(A5+X*A6))))))/1.0e10
        RETURN
        END FUNCTION F7
  END FUNCTION PsyTsatFnHPb
Call graph
psytsatfnhpb calls getsatairenthalpy
getsatairenthalpy calls getsathumratio, getmoistairenthalpy
getsathumratio calls getsatvappres
getmoistairenthalpy calls isip
getsatvappres calls isip, gettrankinefromtfahrenheit, gettkelvinfromtcelsius
calcminimaldxcooling calls psytsatfnhpb
simminimaldxcooling calls calcminimaldxcooling